### ISSUE TITLE
Make TieBreaks into an IEnumerable<TieBreak> again

### ISSUE THREAD

**Issue by ErwanTLG** [jacobhood/Challonge-DotNet#13]
So I noticed that the `TieBreaks` property of the `Tournament` class was converted to an `IEnumerable<TieBreak>` in [2c41a0c](https://github.com/jacobhood/Challonge-DotNet/commit/2c41a0cbbf6f67d5a9544d2e8b2e3ed009f4c99e)
but this change was rollbacked with [1b6d4a6](https://github.com/jacobhood/Challonge-DotNet/commit/1b6d4a6e4e4bbf119163ad70265d6f58c83ff375).

I don't know why it was changed, but I assume it was because it caused some issues because not all the possible values were taken into account. 
If this is the case, here are the possible values that I found when I did some digging:
- `"match wins"`
- `"game wins"`
- `"game win percentage"`
- `"points scored"`
- `"points difference"`
- `"match wins vs tied"`
- `"median buchholz"`

On their [knowledge base](https://kb.challonge.com/en/article/rank-and-tie-break-statistics-1p5f7y4/), Challonge also lists `custom`, however I have not seen it for `tie_breaks` but only for `ranked_by`.

**Comment by jacobhood** [comment]
Hey Erwan, I rolled it back is because I thought modifying the generic type could be a breaking change, and for that reason that it would best be saved for version 2.0.0. I have a couple of other things in mind for that release, but I've been unusually busy recently and haven't gotten around to implementing them. I suppose there's really no reason that change can't be pushed to the repo now though, so I'll do that soon. Thanks for the digging, too.

**Comment by jacobhood** [comment]
Resolved in commit [872942a8869367385dac4ae8e7fac0bf38ac2f88](https://github.com/jacobhood/Challonge-DotNet/commit/872942a8869367385dac4ae8e7fac0bf38ac2f88).
